-- CreateEnum
CREATE TYPE "Parcours" AS ENUM ('COMPREHENSION_LECTURE', 'ECO_CITOYENNETE', 'EDUCATION_CIVIQUE', 'NUMERIQUE', 'ANGLAIS', 'ROBOTIQUE', 'NUMERIQUE_ADULTE', 'ORAL');

-- AlterTable
ALTER TABLE "Module" ADD COLUMN     "parcours" "Parcours"[];
